# Include before the generic PHP location.
location ~* ^/(?:[_0-9a-z-]+/)?wp-content/(?:uploads|cache|upgrade)(?:/.*)?\.(?:php(?:[0-9]+)?|phtml?|phar|inc)$ {
    return 404;
}

location ~* ^/(?:[_0-9a-z-]+/)?wp-content/(?:uploads|cache|upgrade)/(?:.*\/)?\.(?:user\.ini|htaccess)$ {
    return 404;
}
